<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* emails/mail */
class __TwigTemplate_c375807ac11f61a819feed4ec8f511694c51b7b8c11b46677ef05eb0cceafba8 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
            'title' => [$this, 'block_title'],
            'introduction' => [$this, 'block_introduction'],
            'message' => [$this, 'block_message'],
            'footer' => [$this, 'block_footer'],
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        $this->displayBlock('title', $context, $blocks);
        // line 2
        echo "
";
        // line 3
        $this->displayBlock('introduction', $context, $blocks);
        // line 4
        echo "
";
        // line 5
        $this->displayBlock('message', $context, $blocks);
        // line 6
        echo "
";
        // line 7
        $this->displayBlock('footer', $context, $blocks);
    }

    // line 1
    public function block_title($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo twig_escape_filter($this->env, call_user_func_array($this->env->getFunction('__')->getCallable(), ["Hi %s,", [0 => ($context["username"] ?? null)]]), "html", null, true);
    }

    // line 3
    public function block_introduction($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo twig_escape_filter($this->env, call_user_func_array($this->env->getFunction('__')->getCallable(), ["here is a message for you from the %s:", [0 => call_user_func_array($this->env->getFunction('config')->getCallable(), ["app_name"])]]), "html", null, true);
    }

    // line 5
    public function block_message($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo ($context["message"] ?? null);
    }

    // line 7
    public function block_footer($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo twig_escape_filter($this->env, call_user_func_array($this->env->getFunction('__')->getCallable(), ["This email is autogenerated and has not been signed. You got this email because you are registered in the %s.", [0 => call_user_func_array($this->env->getFunction('config')->getCallable(), ["app_name"])]]), "html", null, true);
    }

    public function getTemplateName()
    {
        return "emails/mail";
    }

    public function getDebugInfo()
    {
        return array (  81 => 7,  74 => 5,  67 => 3,  60 => 1,  56 => 7,  53 => 6,  51 => 5,  48 => 4,  46 => 3,  43 => 2,  41 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("", "emails/mail", "/var/www/html/engelsystem/resources/views/emails/mail.twig");
    }
}
